### ISSUE TITLE
Dockerfile uses outdated link to download GeoLite2 databases

### ISSUE THREAD

**Issue by 2shortplanks** [samnissen/maxminddb-docker#4]
Due to upcoming data privacy regulations, MaxMind are making significant changes to how users access free MaxMind GeoLite2 databases starting December 30, 2019. The databases will continue to be available without charge and for redistribution. However, you will be required to create an account and use a license key to download the databases, and agree to a new EULA that addresses applicable data privacy regulations.

Learn more on our blog: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/.

Mark Fowler.
MaxMind.

**Comment by samnissen** [comment]
Thank you @2shortplanks for letting me know - I had missed this completely. Makes sense, and I've updated the app to use personal/private URLs that can be updated per user -- fixed by #6 .
